[package]
name = "playground-utils"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[dependencies.rustup]
version = "1.17"
git = "https://github.com/rust-lang/rustup.rs.git"

