[package]
name = "playground-utils"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2018"

[dependencies]
dirs = "1.0"
serde = "1.0"
serde_derive = "1.0"
semver = "0.9"

[dev-dependencies]
tempdir = "0.3.7"
